name: Build Magisk

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Collect APKs
        run: bash collect-apks.sh

      - name: ZIP module
        run: zip defapps.zip -r ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Module
          path: defapps.zip
